services:
  - type: web
    name: pubhub-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "7d"
      - key: SESSION_DURATION_DAYS
        value: "7"
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_GITHUB_CLIENT_ID
        sync: false
